{
  "stats": {
    "suites": 4,
    "tests": 12,
    "passes": 12,
    "pending": 0,
    "failures": 0,
    "start": "2018-05-16T17:37:55.944Z",
    "end": "2018-05-16T17:37:57.109Z",
    "duration": 1165
  },
  "tests": [
    {
      "title": "fluent interface works",
      "fullTitle": "Basics → fluent interface works",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "create() static class method instantiates",
      "fullTitle": "Basics → create() static class method instantiates",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "using get() utility function for invalid property throws error",
      "fullTitle": "Basics → using get() utility function for invalid property throws error",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "using get() utility function for a valid property works",
      "fullTitle": "Basics → using get() utility function for a valid property works",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "two promises complete within a basic fail-slow scenario",
      "fullTitle": "Basics → two promises complete within a basic fail-slow scenario",
      "duration": 201,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "two promises with the same name send warning to console but still execute",
      "fullTitle": "Basics → two promises with the same name send warning to console but still execute",
      "duration": 204,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "two delayed promises with the same name throw an error",
      "fullTitle": "Basics → two delayed promises with the same name throw an error",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "nested errors are exposed to the message of final error",
      "fullTitle": "Basics → nested errors are exposed to the message of final error",
      "duration": 70,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "One of the promises fails inbetween the successes; fails immediately",
      "fullTitle": "Fail Fast →  One of the promises fails inbetween the successes; fails immediately",
      "duration": 160,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "One of the promises fails quickly but waits until all done",
      "fullTitle": "Fail Slow →  One of the promises fails quickly but waits until all done",
      "duration": 211,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "when a timeout's time limit is exceeded it throws a TimeoutError",
      "fullTitle": "Timeouts → when a timeout's time limit is exceeded it throws a TimeoutError",
      "duration": 157,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "when a timeout is set but completion is before time limit, no error is thrown",
      "fullTitle": "Timeouts → when a timeout is set but completion is before time limit, no error is thrown",
      "duration": 155,
      "currentRetry": 0,
      "err": {}
    }
  ],
  "pending": [],
  "failures": [],
  "passes": [
    {
      "title": "fluent interface works",
      "fullTitle": "Basics → fluent interface works",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "create() static class method instantiates",
      "fullTitle": "Basics → create() static class method instantiates",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "using get() utility function for invalid property throws error",
      "fullTitle": "Basics → using get() utility function for invalid property throws error",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "using get() utility function for a valid property works",
      "fullTitle": "Basics → using get() utility function for a valid property works",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "two promises complete within a basic fail-slow scenario",
      "fullTitle": "Basics → two promises complete within a basic fail-slow scenario",
      "duration": 201,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "two promises with the same name send warning to console but still execute",
      "fullTitle": "Basics → two promises with the same name send warning to console but still execute",
      "duration": 204,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "two delayed promises with the same name throw an error",
      "fullTitle": "Basics → two delayed promises with the same name throw an error",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "nested errors are exposed to the message of final error",
      "fullTitle": "Basics → nested errors are exposed to the message of final error",
      "duration": 70,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "One of the promises fails inbetween the successes; fails immediately",
      "fullTitle": "Fail Fast →  One of the promises fails inbetween the successes; fails immediately",
      "duration": 160,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "One of the promises fails quickly but waits until all done",
      "fullTitle": "Fail Slow →  One of the promises fails quickly but waits until all done",
      "duration": 211,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "when a timeout's time limit is exceeded it throws a TimeoutError",
      "fullTitle": "Timeouts → when a timeout's time limit is exceeded it throws a TimeoutError",
      "duration": 157,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "when a timeout is set but completion is before time limit, no error is thrown",
      "fullTitle": "Timeouts → when a timeout is set but completion is before time limit, no error is thrown",
      "duration": 155,
      "currentRetry": 0,
      "err": {}
    }
  ]
}